# secrets.tf - AWS Secrets Manager stores sensitive values so they are never hardcoded
# in task definitions or environment variables visible in the AWS console.
# ECS pulls these at container startup and injects them as env vars.
/**
  terraform apply                                                                    
        │
        ▼                                                                            
  random_password  ──▶  Secrets Manager  ◀──  your variables
  (DB pass,               (encrypted)         (SMTP, OAuth)                          
   JWT secret)                │                                                      
                              ▼           
                       ECS container startup                                         
                       injects as env vars

  2 secrets are auto-generated by Terraform so we never have to create/rotate them manually
  - db-password - 32-char random password for RDS
  - jwt-secret  - 64-char random string for signing JWTs

  the rest (SMTP, Github, Google) come from our variables.tf values and get stored in Secrets Manager so ECS can fetch them securely at runtime
*/

# Auto-generated random password for RDS
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}?"
}

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "${local.name_prefix}/db-password"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db.result
}

# Auto-generated JWT secret (64 hex chars = 256 bits)
resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${local.name_prefix}/jwt-secret"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}

# SMTP credentials — stored as separate flat secrets (avoids unreliable JSON key extraction)
resource "aws_secretsmanager_secret" "smtp_username" {
  name                    = "${local.name_prefix}/smtp-username"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "smtp_username" {
  secret_id     = aws_secretsmanager_secret.smtp_username.id
  secret_string = var.smtp_username
}

resource "aws_secretsmanager_secret" "smtp_password" {
  name                    = "${local.name_prefix}/smtp-password"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "smtp_password" {
  secret_id     = aws_secretsmanager_secret.smtp_password.id
  secret_string = var.smtp_password
}

# GitHub OAuth2 credentials
resource "aws_secretsmanager_secret" "github_client_id" {
  name                    = "${local.name_prefix}/github-client-id"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "github_client_id" {
  secret_id     = aws_secretsmanager_secret.github_client_id.id
  secret_string = var.github_client_id
}

resource "aws_secretsmanager_secret" "github_client_secret" {
  name                    = "${local.name_prefix}/github-client-secret"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "github_client_secret" {
  secret_id     = aws_secretsmanager_secret.github_client_secret.id
  secret_string = var.github_client_secret
}

# Google OAuth2 credentials
resource "aws_secretsmanager_secret" "google_client_id" {
  name                    = "${local.name_prefix}/google-client-id"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "google_client_id" {
  secret_id     = aws_secretsmanager_secret.google_client_id.id
  secret_string = var.google_client_id
}

resource "aws_secretsmanager_secret" "google_client_secret" {
  name                    = "${local.name_prefix}/google-client-secret"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "google_client_secret" {
  secret_id     = aws_secretsmanager_secret.google_client_secret.id
  secret_string = var.google_client_secret
}
