# secrets.tf - AWS Secrets Manager stores sensitive values so they are never hardcoded
# in task definitions or environment variables visible in the AWS console.
# ECS pulls these at container startup and injects them as env vars.
/**
  terraform apply                                                                    
        │
        ▼                                                                            
  random_password  ──▶  Secrets Manager  ◀──  your variables
  (DB pass,               (encrypted)         (SMTP, OAuth)                          
   JWT secret)                │                                                      
                              ▼           
                       ECS container startup                                         
                       injects as env vars

  2 secrets are auto-generated by Terraform so we never have to create/rotate them manually
  - db-password - 32-char random password for RDS
  - jwt-secret  - 64-char random string for signing JWTs

  the rest (SMTP, Github, Google) come from our variables.tf values and get stored in Secrets Manager so ECS can fetch them securely at runtime
*/

# Auto-generated random password for RDS
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}?"
}

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "${local.name_prefix}/db-password"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db.result
}

# Auto-generated JWT secret (64 hex chars = 256 bits)
resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${local.name_prefix}/jwt-secret"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}

# SMTP credentials (from variables)
resource "aws_secretsmanager_secret" "smtp" {
  name                    = "${local.name_prefix}/smtp"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "smtp" {
  secret_id = aws_secretsmanager_secret.smtp.id
  secret_string = jsonencode({
    username = var.smtp_username
    password = var.smtp_password
  })
}

# GitHub OAuth2 credentials
resource "aws_secretsmanager_secret" "github_oauth" {
  name                    = "${local.name_prefix}/github-oauth"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "github_oauth" {
  secret_id = aws_secretsmanager_secret.github_oauth.id
  secret_string = jsonencode({
    client_id     = var.github_client_id
    client_secret = var.github_client_secret
  })
}

# Google OAuth2 credentials
resource "aws_secretsmanager_secret" "google_oauth" {
  name                    = "${local.name_prefix}/google-oauth"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "google_oauth" {
  secret_id = aws_secretsmanager_secret.google_oauth.id
  secret_string = jsonencode({
    client_id     = var.google_client_id
    client_secret = var.google_client_secret
  })
}
